<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\User;
use App\Models\Student;
use App\Models\Attendance;
use App\Models\Report;
use App\Models\Schedule;
use App\Models\Chat;
use App\Models\Notification;
use App\Models\Registration;
use App\Models\SemesterReport;

class DummySeeder extends Seeder
{
    public function run(): void
    {
        // Admin
        $admin = User::firstOrCreate(
            ['email' => 'admin@example.com'],
            ['name' => 'Admin', 'password' => Hash::make('password'), 'role' => 'admin']
        );

        // Guru
        $guru = User::firstOrCreate(
            ['email' => 'guru@example.com'],
            ['name' => 'Guru', 'password' => Hash::make('password'), 'role' => 'guru']
        );

        // Orang Tua (default)
        $parent = User::firstOrCreate(
            ['email' => 'ortu@example.com'],
            ['name' => 'Orang Tua', 'password' => Hash::make('password'), 'role' => 'orangtua']
        );

        // Hapus data siswa lama sebelum mengisi ulang
        \DB::table('semester_reports')->delete();
        \DB::table('schedules')->delete();
        \DB::table('reports')->delete();
        \DB::table('attendances')->delete();
        \DB::table('students')->delete();

        // Data Peserta Didik TK AL ISTIQOMAH 2025/2026
        $studentsData = [
            [
                'name' => 'ABIL ALTAIR ERDHAFEN',
                'nisn' => '3193713608',
                'nomor_induk' => '119',
                'tempat_lahir' => 'BANDAR LAMPUNG',
                'birth_date' => '2019-12-03',
                'nik' => '1871140312190001',
                'kelas' => 'B1',
                'gender' => 'L',
                'address' => 'JL. UNTUNG SUROPATI PANCA BAKTI NO 61 LK I',
                'nama_ayah' => 'ERPANDI',
                'pekerjaan_ayah' => 'Buruh',
                'nama_ibu' => 'JUMIATI',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'telepon' => '082282746766',
            ],
            [
                'name' => 'AISYAH PUTRI INAYAH',
                'nisn' => '3196671765',
                'nomor_induk' => '120',
                'tempat_lahir' => 'BANDAR LAMPUNG',
                'birth_date' => '2019-10-25',
                'nik' => '1871146510190001',
                'kelas' => 'B1',
                'gender' => 'P',
                'address' => 'JL UNTUNG SUROPATI GG RUKUN 4 LK. II',
                'nama_ayah' => 'HENDRI NOPRIYANTO',
                'pekerjaan_ayah' => 'Buruh',
                'nama_ibu' => 'SORAYA',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'telepon' => '089561006419',
            ],
            [
                'name' => 'AKSYAHRA VYANTA HUMAIRA MECCA',
                'nisn' => '3207566962',
                'nomor_induk' => '122',
                'tempat_lahir' => 'Tulang Bawang',
                'birth_date' => '2020-03-21',
                'nik' => '1811046103200001',
                'kelas' => 'B1',
                'gender' => 'P',
                'address' => 'Jl Raja Ratu Gg Sejahtera 2',
                'nama_ayah' => 'Akbar Syah Putra',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'nama_ibu' => 'FINA ALFIANITA SARI',
                'pekerjaan_ibu' => 'Wiraswasta',
                'telepon' => '082280041105',
            ],
            [
                'name' => 'ALVARO ATHAYA ARIYUN',
                'nisn' => '3202858632',
                'nomor_induk' => '121',
                'tempat_lahir' => 'Bandar Lampung',
                'birth_date' => '2020-11-07',
                'nik' => '1871140711200001',
                'kelas' => 'A',
                'gender' => 'L',
                'address' => 'Jl Untung Suropati LK II',
                'nama_ayah' => 'Ari Kristianto',
                'pekerjaan_ayah' => 'Wiraswasta',
                'nama_ibu' => 'Nurwahyuni',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'telepon' => '081271459987',
            ],
            [
                'name' => 'ANDHANU RHADITYA',
                'nisn' => '3200671971',
                'nomor_induk' => null,
                'tempat_lahir' => 'Bandar Lampung',
                'birth_date' => '2020-03-01',
                'nik' => '1871140103200002',
                'kelas' => 'B2',
                'gender' => 'L',
                'address' => 'Jl Wijaya Kusuma Komp Pancabakti Gg Matahari LK II',
                'nama_ayah' => 'Slamet Riyadi Dame',
                'pekerjaan_ayah' => 'Wiraswasta',
                'nama_ibu' => 'Evi Haryanti',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'telepon' => null,
            ],
            [
                'name' => 'ANDHARU ADITYA',
                'nisn' => '3201524080',
                'nomor_induk' => null,
                'tempat_lahir' => 'Bandar Lampung',
                'birth_date' => '2020-03-01',
                'nik' => '1871140103200001',
                'kelas' => 'B2',
                'gender' => 'L',
                'address' => 'Jl Wijaya Kusuma Komp Pancabakti Gg Matahari VII LK II',
                'nama_ayah' => 'Slamet Riyadi Dame',
                'pekerjaan_ayah' => 'Wiraswasta',
                'nama_ibu' => 'Evi Haryanti',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'telepon' => null,
            ],
            [
                'name' => 'ANINDIRA CHAYRA PRATISTA',
                'nisn' => '3200846419',
                'nomor_induk' => '124',
                'tempat_lahir' => 'BANDAR LAMPUNG',
                'birth_date' => '2020-04-09',
                'nik' => '1871144904200001',
                'kelas' => 'B2',
                'gender' => 'P',
                'address' => 'JL. UNTUNG SUROPATI GG. SEPAKAT NO 1A LK II',
                'nama_ayah' => 'ANDRI HADI',
                'pekerjaan_ayah' => 'Wiraswasta',
                'nama_ibu' => 'MENIK ANJARWATI',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'telepon' => '085758922300',
            ],
            [
                'name' => 'AQILA ZALFA HASANAH',
                'nisn' => '3208035104',
                'nomor_induk' => '125',
                'tempat_lahir' => 'BANDAR LAMPUNG',
                'birth_date' => '2020-01-14',
                'nik' => '1871165401200001',
                'kelas' => 'B1',
                'gender' => 'P',
                'address' => 'JL. UNTUNG SUROPATI GG. FAMILY 6',
                'nama_ayah' => 'HASAN NUDIN',
                'pekerjaan_ayah' => 'Buruh',
                'nama_ibu' => 'AULIA BUNGA SAFITRI',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'telepon' => '083863766583',
            ],
            [
                'name' => 'ARRASYA NATHANAEL WIDIANTO',
                'nisn' => null,
                'nomor_induk' => '126',
                'tempat_lahir' => 'BANDAR LAMPUNG',
                'birth_date' => '2019-11-13',
                'nik' => '1871051311190005',
                'kelas' => 'B2',
                'gender' => 'L',
                'address' => 'JL. SRIKRESNA GG. WARU 20',
                'nama_ayah' => 'AL ROY TRIWIDIANTO',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'nama_ibu' => 'PUTRI MEIKA ANDRIANI',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'telepon' => '08988142292',
            ],
            [
                'name' => 'ARSYILA RAFIFAH ADELIA',
                'nisn' => '3191726611',
                'nomor_induk' => '127',
                'tempat_lahir' => 'BANDAR LAMPUNG',
                'birth_date' => '2019-11-27',
                'nik' => '1871146711190001',
                'kelas' => 'B1',
                'gender' => 'P',
                'address' => 'JL UNTUNG SUROPATI GG RAJA RATU LK I',
                'nama_ayah' => 'JULIYANTO',
                'pekerjaan_ayah' => 'Wiraswasta',
                'nama_ibu' => 'APRILIYAWATI',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'telepon' => '0895700660440',
            ],
            [
                'name' => 'ATHALLA MAHER',
                'nisn' => '3198334668',
                'nomor_induk' => '123',
                'tempat_lahir' => 'BOGOR',
                'birth_date' => '2019-12-28',
                'nik' => '3271062812190005',
                'kelas' => 'B1',
                'gender' => 'L',
                'address' => 'JL WIJAYA KUSUMA GG MATAHARI 4',
                'nama_ayah' => 'JANSSEN CAHYADI',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'nama_ibu' => 'PUTRI SYADZA SAUSAN',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'telepon' => '0895618980507',
            ],
            [
                'name' => 'CHEISYA SALSABILA',
                'nisn' => '3199983429',
                'nomor_induk' => '128',
                'tempat_lahir' => 'Bandar Lampung',
                'birth_date' => '2019-12-25',
                'nik' => '1871146512190001',
                'kelas' => 'B1',
                'gender' => 'P',
                'address' => 'Jl. Untung Suropati P. Bakti Gg. asoka no 94 LK III',
                'nama_ayah' => 'Beny Septianto',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'nama_ibu' => 'Vivi Selvia Athaga',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'telepon' => null,
            ],
            [
                'name' => 'DEWI HAFIZAH IRWANA',
                'nisn' => '3192155289',
                'nomor_induk' => '130',
                'tempat_lahir' => 'BANDAR LAMPUNG',
                'birth_date' => '2019-06-30',
                'nik' => '1871027006190002',
                'kelas' => 'B1',
                'gender' => 'P',
                'address' => 'JL WIJAYA KUSUMA PERUM PANCABAKTI LK II',
                'nama_ayah' => 'IRAWAN SUKI',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'nama_ibu' => 'IRNA WATI',
                'pekerjaan_ibu' => 'Karyawan Swasta',
                'telepon' => '08133132380661',
            ],
            [
                'name' => 'DIRGA ANDRIAN',
                'nisn' => '3195197158',
                'nomor_induk' => '129',
                'tempat_lahir' => 'Bandar Lampung',
                'birth_date' => '2019-12-17',
                'nik' => '1871141712190003',
                'kelas' => 'B1',
                'gender' => 'L',
                'address' => 'Komp Perum Pancabakti No 63',
                'nama_ayah' => 'Andrian Suryana',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'nama_ibu' => 'Kencana Wulan sari',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'telepon' => '088286242966',
            ],
            [
                'name' => 'KHAIRA NADHIFA SATRIYA JASA',
                'nisn' => '3209801539',
                'nomor_induk' => '132',
                'tempat_lahir' => 'BANDAR LAMPUNG',
                'birth_date' => '2020-02-18',
                'nik' => '1871105802200001',
                'kelas' => 'B2',
                'gender' => 'P',
                'address' => 'JL. SRIKRISNA KP BAYUR',
                'nama_ayah' => 'JONI SATRIYA',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'nama_ibu' => 'FIZRI VIA AGUSTINA',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'telepon' => '081274568944',
            ],
            [
                'name' => 'LUTHPI HASBI',
                'nisn' => '3196466268',
                'nomor_induk' => '134',
                'tempat_lahir' => 'SIMALUNGUN',
                'birth_date' => '2019-08-09',
                'nik' => '1208030908190001',
                'kelas' => 'B2',
                'gender' => 'L',
                'address' => 'Jl Soekarno Hatta LK I',
                'nama_ayah' => 'Nazarudin',
                'pekerjaan_ayah' => 'Wiraswasta',
                'nama_ibu' => 'TIO DORMA SILALAHI',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'telepon' => null,
            ],
            [
                'name' => 'M. RAFFA ALFATIH AFRIYADI',
                'nisn' => '3201575054',
                'nomor_induk' => '144',
                'tempat_lahir' => 'SOLO',
                'birth_date' => '2020-11-22',
                'nik' => '1871102211200001',
                'kelas' => 'A',
                'gender' => 'L',
                'address' => 'Jl. Untung Suropati Gg Harum No 65',
                'nama_ayah' => 'Ujang Afriyadi',
                'pekerjaan_ayah' => 'Wiraswasta',
                'nama_ibu' => 'Diana Utami Putri Apandi',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'telepon' => '085273678410',
            ],
            [
                'name' => 'MAHENDRA ANDRIAN',
                'nisn' => '3219058996',
                'nomor_induk' => null,
                'tempat_lahir' => 'Bandar Lampung',
                'birth_date' => '2021-03-10',
                'nik' => '1871141003210001',
                'kelas' => 'A',
                'gender' => 'L',
                'address' => 'Komp. Perum Pancabakti No 63',
                'nama_ayah' => 'Andrian Suryana',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'nama_ibu' => 'Kencana Wulan Sari',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'telepon' => null,
            ],
            [
                'name' => 'MARYAM GEBRINA KUSUMA',
                'nisn' => '3193605334',
                'nomor_induk' => '131',
                'tempat_lahir' => 'BANDAR LAMPUNG',
                'birth_date' => '2019-09-14',
                'nik' => '1871175409190001',
                'kelas' => 'B1',
                'gender' => 'P',
                'address' => 'JL FLAMBOYAN GG.SADAR NO.8 LK.II',
                'nama_ayah' => 'ARIA KUSUMA',
                'pekerjaan_ayah' => 'Wiraswasta',
                'nama_ibu' => 'PUJI SAKA ANGGRAINI',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'telepon' => '083866483095',
            ],
            [
                'name' => 'MUHAMMAD AMMAR FADHILAH',
                'nisn' => '3203532466',
                'nomor_induk' => '148',
                'tempat_lahir' => 'BANDAR LAMPUNG',
                'birth_date' => '2020-12-03',
                'nik' => '1871140312200001',
                'kelas' => 'A',
                'gender' => 'L',
                'address' => 'JL. WIJAYA KUSUMA PANCA BAKTI NO. 8 LK. II',
                'nama_ayah' => 'ALEK EFENDI',
                'pekerjaan_ayah' => 'Lainnya',
                'nama_ibu' => 'ANGGRAENI DWI PUSPITASARI',
                'pekerjaan_ibu' => 'Lainnya',
                'telepon' => '089529894444',
            ],
            [
                'name' => 'MUHAMMAD MIKAIL WIJAYA',
                'nisn' => '3205821892',
                'nomor_induk' => '145',
                'tempat_lahir' => 'Bandar Lampung',
                'birth_date' => '2020-10-22',
                'nik' => '1871142210200001',
                'kelas' => 'A',
                'gender' => 'L',
                'address' => 'Jl Untung Suropati Gg Tanjung No 179 LK II',
                'nama_ayah' => 'INDRA WIJAYA',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'nama_ibu' => 'QONAATUL CHOIRO',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'telepon' => '081990518952',
            ],
            [
                'name' => 'MUHAMMAD ZABDAN ANDRIAN',
                'nisn' => '3211693324',
                'nomor_induk' => '133',
                'tempat_lahir' => 'BANDAR LAMPUNG',
                'birth_date' => '2021-03-18',
                'nik' => '1871141803210003',
                'kelas' => 'A',
                'gender' => 'L',
                'address' => 'KOMP. P PANCA BAKTI GG. TANJUNG LK III',
                'nama_ayah' => 'HERRI ADINATA',
                'pekerjaan_ayah' => 'PNS/TNI/Polri',
                'nama_ibu' => 'INDAH PUTRI AGUSTINA',
                'pekerjaan_ibu' => 'PNS/TNI/Polri',
                'telepon' => '082176151536',
            ],
            [
                'name' => 'NAUFAL RAMADHAN',
                'nisn' => '3209376025',
                'nomor_induk' => '138',
                'tempat_lahir' => 'GUNUNG SUGIH BESAR',
                'birth_date' => '2020-05-01',
                'nik' => '3603020105200002',
                'kelas' => 'B2',
                'gender' => 'L',
                'address' => 'KAMPUNG BARU',
                'nama_ayah' => 'AHMAD YANI',
                'pekerjaan_ayah' => 'Wiraswasta',
                'nama_ibu' => 'ELA LASTARI',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'telepon' => '085269119394',
            ],
            [
                'name' => 'NAYLA NANDA PUTRI',
                'nisn' => '3202483333',
                'nomor_induk' => '135',
                'tempat_lahir' => 'BANDAR LAMPUNG',
                'birth_date' => '2020-03-23',
                'nik' => '1871146303200002',
                'kelas' => 'B2',
                'gender' => 'P',
                'address' => 'JL UNTUNG SUROPATI GG RAJA RATU LK I',
                'nama_ayah' => 'SOMAD PINANDA',
                'pekerjaan_ayah' => 'Petani',
                'nama_ibu' => 'TUTI MARYATI',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'telepon' => '081532722932',
            ],
            [
                'name' => 'REINA MECCA KURNIAWAN',
                'nisn' => '3201201694',
                'nomor_induk' => '146',
                'tempat_lahir' => 'BANDAR LAMPUNG',
                'birth_date' => '2020-10-19',
                'nik' => '1871145910200002',
                'kelas' => 'A',
                'gender' => 'P',
                'address' => 'JL. BUMI MANTI GG. SURYA KENCANA NO.21 LK I',
                'nama_ayah' => 'ARI KURNIAWAN SAPUTRA',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'nama_ibu' => 'CAHYANI MUTIARAWAN P',
                'pekerjaan_ibu' => 'Karyawan Swasta',
                'telepon' => '082175824510',
            ],
            [
                'name' => 'RENATA ARSY SUSILO',
                'nisn' => '3206861787',
                'nomor_induk' => '139',
                'tempat_lahir' => 'Bandar Lampung',
                'birth_date' => '2020-04-30',
                'nik' => '1871147004200001',
                'kelas' => 'B2',
                'gender' => 'P',
                'address' => 'Jl Untung Suropati Gg Tanjung No 20',
                'nama_ayah' => 'Ari Susilo, S.Kom',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'nama_ibu' => 'Faradillah Chairunnisa, S.P',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'telepon' => '081231087001',
            ],
            [
                'name' => 'REYHAN ALFA RISKI',
                'nisn' => '3199561634',
                'nomor_induk' => '137',
                'tempat_lahir' => 'BANDAR LAMPUNG',
                'birth_date' => '2019-09-14',
                'nik' => '1871111409190002',
                'kelas' => 'B1',
                'gender' => 'L',
                'address' => 'JL.S.HATTA GG.PEPAYA I NO.20',
                'nama_ayah' => 'THONI RISWANDI',
                'pekerjaan_ayah' => 'Buruh',
                'nama_ibu' => 'SUTINAH',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'telepon' => null,
            ],
            [
                'name' => 'SALAHUDDIN KAHFI PRAWIRANEGARA',
                'nisn' => '3208144690',
                'nomor_induk' => '140',
                'tempat_lahir' => 'Bandar Lampung',
                'birth_date' => '2020-01-02',
                'nik' => '1871140201200001',
                'kelas' => 'B2',
                'gender' => 'L',
                'address' => 'Jl Wijaya Kusuma Gg Mawar Perum Golden Green Estate LK II',
                'nama_ayah' => 'Agung Setiawan, SH. MH',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'nama_ibu' => 'Ika Kusumawardani',
                'pekerjaan_ibu' => 'Karyawan Swasta',
                'telepon' => '081379014810',
            ],
            [
                'name' => 'SHEZAN NAILA SALSABILA',
                'nisn' => '3192524958',
                'nomor_induk' => '136',
                'tempat_lahir' => 'BANDAR LAMPUNG',
                'birth_date' => '2019-11-29',
                'nik' => '1871146911190001',
                'kelas' => 'B2',
                'gender' => 'P',
                'address' => 'JL WIJAYA KUSUMA GG TANJUNG NO 174 LK II',
                'nama_ayah' => 'MUHAMAD RIZKI',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'nama_ibu' => 'DINI OKTAVIANTI',
                'pekerjaan_ibu' => 'Karyawan Swasta',
                'telepon' => '089644228742',
            ],
            [
                'name' => 'SYAFIQ RADEVA VERDIANTO',
                'nisn' => '3206973252',
                'nomor_induk' => '141',
                'tempat_lahir' => 'Bandar Lampung',
                'birth_date' => '2020-03-31',
                'nik' => '1871143103200004',
                'kelas' => 'B1',
                'gender' => 'L',
                'address' => 'Jl Untung Suropati Gg Rukun 2 LK II',
                'nama_ayah' => 'Jefri yanto',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'nama_ibu' => 'Febri Ratna Sari',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'telepon' => null,
            ],
            [
                'name' => 'TEGUH SATRIA',
                'nisn' => '3207434745',
                'nomor_induk' => '142',
                'tempat_lahir' => 'BANDAR LAMPUNG',
                'birth_date' => '2020-01-31',
                'nik' => '1871143101200001',
                'kelas' => 'B1',
                'gender' => 'L',
                'address' => 'JL UNTUNG SUROPATI GG RUKUN I LK I',
                'nama_ayah' => 'ENDI HERMAWAN',
                'pekerjaan_ayah' => 'Buruh',
                'nama_ibu' => 'UMIGA UTAMI',
                'pekerjaan_ibu' => 'Karyawan Swasta',
                'telepon' => '0895323160753',
            ],
            [
                'name' => 'WILDAN AMRILAH',
                'nisn' => '3191730870',
                'nomor_induk' => '143',
                'tempat_lahir' => 'BANDAR LAMPUNG',
                'birth_date' => '2019-04-11',
                'nik' => '1871141104190003',
                'kelas' => 'B1',
                'gender' => 'L',
                'address' => 'JL UNTUNG SUROPATI GG MAKARTI LK II',
                'nama_ayah' => 'YANA RODIANA',
                'pekerjaan_ayah' => 'Buruh',
                'nama_ibu' => 'USNIAWATI',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'telepon' => '081274811062',
            ],
            [
                'name' => 'YUKI MAHARANI',
                'nisn' => '3218872635',
                'nomor_induk' => null,
                'tempat_lahir' => 'Lampung Barat',
                'birth_date' => '2021-03-21',
                'nik' => '1804116103210001',
                'kelas' => 'A',
                'gender' => 'P',
                'address' => 'Jl Untung Suropati Gg Dahlia',
                'nama_ayah' => 'Hendriawan',
                'pekerjaan_ayah' => 'Wiraswasta',
                'nama_ibu' => 'Diana Febriana',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'telepon' => null,
            ],
            [
                'name' => 'ZEVANYA KIMBERLY',
                'nisn' => '3208775515',
                'nomor_induk' => '147',
                'tempat_lahir' => 'BANDAR LAMPUNG',
                'birth_date' => '2020-09-25',
                'nik' => '1871146509200001',
                'kelas' => 'A',
                'gender' => 'P',
                'address' => 'JL UNTUNG SUROPATI GG RUKUN II LK II',
                'nama_ayah' => 'ADI SETIAWAN',
                'pekerjaan_ayah' => 'Buruh',
                'nama_ibu' => 'INDAH WAHYU SETIAWATI',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'telepon' => null,
            ],
            [
                'name' => 'ERLANGGA PRADIPTA BIMANTARA',
                'nisn' => null,
                'nomor_induk' => '149',
                'tempat_lahir' => null,
                'birth_date' => null,
                'nik' => null,
                'kelas' => 'A',
                'gender' => 'L',
                'address' => null,
                'nama_ayah' => null,
                'pekerjaan_ayah' => null,
                'nama_ibu' => null,
                'pekerjaan_ibu' => null,
                'telepon' => null,
            ],
            [
                'name' => 'ISHKA AGNIA',
                'nisn' => null,
                'nomor_induk' => '150',
                'tempat_lahir' => null,
                'birth_date' => null,
                'nik' => null,
                'kelas' => 'A',
                'gender' => 'P',
                'address' => null,
                'nama_ayah' => null,
                'pekerjaan_ayah' => null,
                'nama_ibu' => null,
                'pekerjaan_ibu' => null,
                'telepon' => null,
            ],
        ];

        $firstStudent = null;
        foreach ($studentsData as $i => $data) {
            $student = Student::create(array_merge($data, ['parent_id' => $parent->id]));
            if ($i === 0) {
                $firstStudent = $student;
            }
        }

        // Contoh data pendukung untuk siswa pertama
        Attendance::create([
            'student_id' => $firstStudent->id,
            'teacher_id' => $guru->id,
            'date' => now(),
            'status' => 'Hadir',
            'note' => 'Hadir tepat waktu',
        ]);

        Report::create([
            'student_id' => $firstStudent->id,
            'teacher_id' => $guru->id,
            'week_start' => now()->startOfWeek(),
            'cognitive' => 80,
            'motoric' => 85,
            'social' => 90,
            'language' => 88,
            'note' => 'Perkembangan baik',
        ]);

        Schedule::create([
            'student_id' => $firstStudent->id,
            'teacher_id' => $guru->id,
            'type' => 'bk',
            'date' => now()->addDays(2),
            'description' => 'Konseling mingguan',
        ]);

        Chat::create([
            'sender_id' => $guru->id,
            'receiver_id' => $parent->id,
            'message' => 'Assalamualaikum, ini laporan perkembangan anak Anda.',
            'is_read' => false,
        ]);

        Notification::create([
            'user_id' => $parent->id,
            'message' => 'Laporan perkembangan anak telah diupdate.',
            'read' => false,
        ]);

        Registration::create([
            'kode_pendaftaran' => 'REG-' . strtoupper(substr(md5(time()), 0, 6)),
            'nama_lengkap' => 'Siswa Baru',
            'tempat_lahir' => 'Jakarta',
            'tanggal_lahir' => '2020-06-15',
            'jenis_kelamin' => 'L',
            'alamat_siswa' => 'Jl. Contoh No.2, Jakarta',
            'nama_ayah' => 'Ayah Siswa Baru',
            'nama_ibu' => 'Ibu Siswa Baru',
            'pekerjaan_ayah' => 'Wiraswasta',
            'pekerjaan_ibu' => 'Ibu Rumah Tangga',
            'telepon' => '08123456789',
            'email' => 'ortu.baru@example.com',
            'alamat_ortu' => 'Jl. Contoh No.2, Jakarta',
            'status' => 'pending',
        ]);

        SemesterReport::create([
            'student_id' => $firstStudent->id,
            'teacher_id' => $guru->id,
            'tahun_ajaran' => '2025/2026',
            'semester' => 'Ganjil',
            'kelas' => 'TK B1',
            'agama_moral' => 'BSH',
            'agama_moral_deskripsi' => 'Anak sudah mampu melaksanakan ibadah sederhana (berdoa sebelum dan sesudah makan), mengenal ciptaan Tuhan, serta menunjukkan sikap santun dan hormat kepada guru dan teman.',
            'fisik_motorik' => 'BSB',
            'fisik_motorik_deskripsi' => 'Anak sangat aktif dalam kegiatan motorik kasar seperti berlari dan melompat. Motorik halus juga berkembang baik, mampu memegang pensil dengan benar dan mewarnai dalam garis.',
            'kognitif' => 'BSH',
            'kognitif_deskripsi' => 'Anak mampu mengenal angka 1-10, menghitung benda konkrit, mengenal warna dasar, dan menyelesaikan puzzle sederhana dengan baik.',
            'bahasa' => 'BSH',
            'bahasa_deskripsi' => 'Anak mampu berkomunikasi dengan jelas, menceritakan pengalaman sederhana, mengenal huruf vokal, dan menyimak cerita dengan antusias.',
            'sosial_emosional' => 'BSH',
            'sosial_emosional_deskripsi' => 'Anak dapat bermain bersama teman, berbagi mainan, mengantri dengan tertib, dan menunjukkan empati ketika teman sedih.',
            'seni' => 'BSB',
            'seni_deskripsi' => 'Anak sangat kreatif dalam kegiatan seni, suka menggambar dan mewarnai, aktif bernyanyi dan mengikuti gerak lagu dengan semangat.',
            'hadir' => 85,
            'izin' => 3,
            'sakit' => 2,
            'alpa' => 0,
            'catatan_guru' => 'Ananda menunjukkan perkembangan yang sangat baik selama semester ini.',
            'rekomendasi' => 'Disarankan untuk terus memberikan stimulasi membaca di rumah dengan buku cerita bergambar.',
            'tanggal_terbit' => now()->subMonths(1),
        ]);
    }
}
